spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-5k0j8utk.bj.tencentcdb.com:10176/dbbackend?serverTimezone=UTC
    username: root
    password: root@ruowei
  jpa:
    hibernate:
      ddl-auto: update  #      保留原来值
#          ddl-auto: create #不保留原来数据
    show-sql: true